---
- name: Run depenedencies example
  hosts: localhost


  tasks:


    - name: Include the primary role for example
      ansible.builtin.include_role:
        name: roles/they


    - name: Print messeage when all roles have ran successfully
      ansible.builtin.debug:
        msg: "{{ k }} {{ dot }} {{ the }} {{ goat }}"

    
