---
# tasks file for they
- name: Set fact for localhost
  ansible.builtin.set_fact:
    k: "They"

- name: remind to set the dependencies
  ansible.builtin.debug:
    msg: "Make sure to include the other dependicies - as Kdot would say 'Whop whop whop whop better do your stuff'"

