on: [push, pull_request]

jobs:
  run-playbook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Run Ansible Playbook
      uses: dawidd6/action-ansible-playbook@v2.8.0
      with:
        playbook: ansible-demos/dependencies-example.yml
        requirements: ansible-demos/requirements.yml